import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Heading } from "grommet";
import { Grommet } from "grommet";
import { deepMerge } from "grommet/utils";
import { grommet } from "grommet/themes";
import ReelSet from "./reelSet";
import React from "react";
import customTheme from "../constants/style";

interface Props {}

class Home extends React.Component<Props> {
  public reelSet: ReelSet | null;

  constructor(props: Props) {
    super(props);
    this.reelSet = null;
  }

  render() {
    return (
      <Grommet
        theme={deepMerge(grommet, customTheme)}
        style={{
          backgroundColor: "#000",
        }}
      >
        <div className={styles.container}>
          <Head>
            <title>DEMONZ SLOTS</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <main className={styles.main}>
            <Heading>DEMONZ SLOTS</Heading>

            <div className={styles.grid}>
              <ReelSet />
            </div>
          </main>

          <footer className={styles.footer}>
            <a
              href="https://cryptodemonz.com/"
              target="_blank"
              rel="noopener noreferrer"
            >
              Powered by CryptoDemonz
            </a>
          </footer>
        </div>
      </Grommet>
    );
  }
}

export default Home;
